Repository ember-tooling/ember-eslint-parser, pull requests merged in 2023-12, with the labels that each got.

#1 Move parser and add boilerplate
  .eslintrc.js
  .prettierrc.js
  package.json
  pnpm-lock.yaml
  src/parser/gjs-gts-parser.js
  src/parser/transforms.js
  src/parser/ts-patch.js
  src/preprocessor/noop.js
  src/utils/document.js
  tests/fixtures/bar.gts
  tests/fixtures/baz.ts
  tests/fixtures/foo.gts
  tests/fixtures/tsconfig.eslint.json
Labels: enhancement

#3 Deps: Upgrade release-plan
  package.json
  pnpm-lock.yaml
Labels: internal

#7 Fix requires of the transforms module
  .eslintrc.js
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
  src/parser/gjs-gts-parser.js
  src/parser/ts-patch.js
Labels: bug

#6 always notify if not correctly setup
  src/preprocessor/noop.js
Labels: bug

#10 Add the noop preprocessor-to-exports
  package.json
  src/preprocessor/noop.js
Labels: enhancement

#11 Add light README
  README.md
Labels: documentation

#13 Run eslint-plugin-ember's tests with every change
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
  scripts/eslint-plugin-ember-test.mjs
Labels: internal

#14 Resolve "Parsing error: Cannot read properties of null"
  .eslintignore
  .github/workflows/ci.yml
  .prettierignore
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  src/parser/transforms.js
  test-projects/gts/.eslintrc.cjs
  test-projects/gts/package.json
  test-projects/gts/src/footer.gts
Labels: bug

#15 fix named block
  src/parser/transforms.js
Labels: bug

#18 'this' is undefined
  src/parser/transforms.js
  test-projects/gts/src/await.gts
Labels: bug

#21 Fix Incorrectly missing scope
  src/parser/transforms.js
  test-projects/gts/src/placeholder.gts
Labels: bug

#22 `<@argument>` Parsing error: Cannot read properties of null (reading 'index')
  src/parser/transforms.js
  test-projects/gts/src/menu.gts
Labels: bug

#20 fix rust utf8 ranges vs js utf16 ranges
  src/parser/transforms.js
  test-projects/gts/src/copy-menu.gts
Labels: bug
