Repository ember-tooling/ember-eslint-parser, pull requests merged in 2024-02, with the labels that each got.

#41 GJS: Add tests to ensure flat-configs work with the parser
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test-projects/configs/flat-js/eslint.config.mjs
  test-projects/configs/flat-js/package.json
  test-projects/configs/flat-js/src/await.gjs
  test-projects/configs/flat-js/src/copy-menu.gjs
  test-projects/configs/flat-js/src/destructure-to-array.gjs
  test-projects/configs/flat-js/src/footer.gjs
  test-projects/configs/flat-js/src/icons.gjs
  test-projects/configs/flat-js/src/menu.gjs
  test-projects/configs/flat-js/src/placeholder.gjs
  test-projects/configs/flat-js/src/services/example.js
  test-projects/gjs/package.json
  test-projects/gts/package.json
  test-projects/rules/padding-line-between-statements/package.json
Labels: internal

#49 fix typed linting
  package.json
  pnpm-lock.yaml
  src/parser/gjs-gts-parser.js
  src/parser/transforms.js
  src/parser/ts-patch.js
  test-projects/gts/.eslintrc.cjs
  test-projects/gts/index.d.ts
  test-projects/gts/package.json
  test-projects/gts/src/await.gts
  test-projects/gts/src/copy-menu.gts
  test-projects/gts/src/menu.gts
  test-projects/gts/src/placeholder-ts.ts
  test-projects/gts/src/placeholder.gts
  test-projects/gts/src/test-decorators.ts
  test-projects/gts/src/test.ts
  test-projects/gts/tsconfig.json
Labels: bug

#50 do not add extra keys to the VisitorKeys map
  src/parser/transforms.js
Labels: bug

#52 Update eslint-plugin-ember script
  scripts/eslint-plugin-ember-test.mjs
Labels: internal

#53 add visitor keys test
  package.json
  pnpm-lock.yaml
  tests/parser.test.js
Labels: internal

#55 fix location info
  src/parser/transforms.js
Labels: bug

#59 add extraFileExtensions by default
  src/parser/gjs-gts-parser.js
  test-projects/gts/.eslintrc.cjs
Labels: bug

#60 use typescript parser by default
  README.md
  src/parser/gjs-gts-parser.js
Labels: bug

#62 Add test situation to verify if imports from gts no longer accidentally are cast to `any`
  test-projects/gts/src/await.gts
  test-projects/gts/src/test.ts
Labels: internal

#63 TypeScript: Support imports without extensions
  src/parser/ts-patch.js
  test-projects/gts/.eslintignore
  test-projects/gts/src/test.ts
Labels: bug

#66 bump ts deps
  package.json
  pnpm-lock.yaml
Labels: enhancement
